spring:
  datasource:
    url: jdbc:mysql://localhost:3320/rental_db?useSSL=false&serverTimezone=UTC
    username: jddc
    password: jddc
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect